### ISSUE TITLE
Error on version 4.3.3 via Swift Package Manager

### ISSUE THREAD

**Issue by mg-partec** [Lightstreamer/Lightstreamer_iOS_Client#1]
Hi,

I am getting an error from Xcode when trying to use version 4.3.3 (4.3.2 works fine) via SPM:

Revision dc59905204a7c78f80ff560d0fc102ece77989bO for lightstreamer_ios_client
remoteSourceControl https://github.com/ Lightstreamer/Lightstreamer_iOS_Client.git
version 4.3.3 does not match previously recorded value
e1e77deeed65d6f9cd054ac8fc11e5f1a88eb8b8

Mattia

**Comment by acarioni** [comment]
Can you try to build [this demo](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-ios/releases/tag/latest-for-client-4.x) with the version 4.3.3?
If you can't, what errors are you encountering?

**Comment by mg-partec** [comment]
Same error from SPM, see screenshot below. I am running Xcode 15.3 (15E204a) on macOS Sonoma 14.4.1
<img width="519" alt="Screenshot 2024-04-22 at 17 44 37" src="https://github.com/Lightstreamer/Lightstreamer_iOS_Client/assets/6928109/f91bc899-d01e-45b0-9f75-0fa32301833f">

**Comment by acarioni** [comment]
I'm also using Xcode 15.3 on Sonoma 14.4.1 and haven't encountered any issues. 
Maybe the problem you're experiencing is related to the SPM cache. 
Have you looked at [this post](https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7) on SO?

**Comment by mg-partec** [comment]
Thanks, the SPM cache reset solved the issue!
